individual book pages
friends-library/dev pull request #65
Opened 2023-08-14 15:38 UTC by kiahjh

2023-08-21 14:23 UTC, jaredh159 requested changes
lots of solid stuff here, thanks. left some comments, plus here are some other miscellaneous thing:

1. the "spin book" icon -- i think the old one is better here, it feels more like spinning the book in 3d rather than the new icon which seems sort of more like a "refresh" icon. can you restore the old icon for that one? i'm ok with the other icon changes you made

2. in the download wizard, the underline style under "learn more about edition" changed -- was this intentional? i think i like the old style better here, but if you felt strongly i could easily let it go.

3. the part of the download wizard where it says "your download will begin shortly" looks different, it used to go full width, now it's sort of framed all around. was this an intentional design change? i think i like the original style here as well, though again, i can flex.

4. i don't see that you brought over any stories.  i think there are at least some stories for all of the download wizard stuff, right? can you check carefully for all the components you brought over in this PR, making sure we don't lose stories?

5. in the document meta list area underneath the description, the diamonds don't appear to be showing.

6. the alternate spanish links (like for example on Alice Hayes) aren't linking to the alternate language site.  this is not perfectly straightforward, but it's not horrible either. check out the old `env.ts` for some possibly helpful code for deriving the alternate site url.

2023-08-21 14:23 UTC, jaredh159 commented on apps/next-evans/pages/book/[friend_slug]/[book_slug].tsx
> +          newestEdition.size === `xlCondensed` ? `xl` : newestEdition.size,
here's another example of that same type conversion

2023-08-23 15:40 UTC, kiahjh commented on apps/next-evans/components/pages/document/DocBlock.tsx
> +        `DocBlock [background-image:linear-gradient(transparent_0%,transparent_105px,rgb(240,240,240)_105px,rgb(240,240,240)_375px,transparent_375px)] [&_a:link]:cursor-pointer [&_a:link]:[border-bot
Yeah, it's being used as a selector as well

2023-08-30 16:54 UTC, jaredh159 approved these changes

2023-08-30 16:55 UTC, merged